### ISSUE TITLE
language-sql wrongly interprets backslash as escaping char for varchars.

### ISSUE THREAD

**Issue by yaras** [atom/language-sql#61] opened 2017-04-14 05:43 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`language-sql` wrongly interprets backslash as escaping char for varchars.

### Steps to Reproduce

1. Add content:
```sql
begin
  dbms_output.put_line('First line');
  
  dbms_output.put_line('\');
  
  dbms_output.put_line('Second line');
end;
```
2. Change syntax to SQL

**Expected behavior:**

Line `  dbms_output.put_line('Second line');` should be formatted exactly as `  dbms_output.put_line('First line');`

**Actual behavior:**

![language-sql](https://cloud.githubusercontent.com/assets/4586383/25034332/c9ff0b1e-20e5-11e7-88cb-a6b01e011f59.png)

**Reproduces how often:**

100%

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Windows: 10
language-sql: 0.25.4

**Comment by dorian-marchal** [comment] 2018-09-11 09:36
same issue

**Comment by Akaizoku** [comment] 2018-09-18 08:27
Duplicate of #13 

Still has not been fixed since May 2015.

**Comment by Arcanemagus** [comment] 2018-09-18 20:26
Thanks for pointing that out @Akaizoku 😉.

We noticed that this is a duplicate of https://github.com/atom/language-sql/issues/13. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-09-18 20:26 UTC
Labels: bug
